# grid-columns: 3
direction: right
# horizontal-gap: 500

User: {
    grid-rows:2
    style.font-size: 100

    웹 페이지 접속: {
        style.font-size: 60
    }

    식당 정보 확인: {
        style.font-size: 60
    }
}

Server: {
    label.near: bottom-center
    style.font-size: 100
    #height: 500
    #width: 700
    # grid-rows: 6
    # horizontal-gap: 200
    # vertical-gap: 200
    
    식당 정보: {
        style.font-size: 60
        #grid-columns: 3
        #grid-columns: 4
        
        식당 정보 요청: {
            style.font-size: 45
        }
        
        데이터 베이스 요청: {
            style.font-size: 45
        }
        
        식당 정보 전달: {
            style.font-size: 45
        }

        # __EMPTY1__.style.opacity: 0
    }

    유저 정보 관리: {
        style.font-size: 60
        
        회원 정보 확인:{
            style.font-size: 45
        }
        회원가입: {
            style.font-size: 45
        }
        로그인: {
            style.font-size: 45
        }
    }

    예약 처리: {
        #grid-rows: 2
        style.font-size: 60
        
        예약 요청: {
            style.font-size: 45
        }
        예약 처리: {
            style.font-size: 45
        }

    }
}

Restourant: {
    
    style.font-size: 80
    height: 500
    width: 700
    # grid-rows: 3
    # grid-columns: 2
    # horizontal-gap: 150
    
}

Server.예약 처리.예약 요청 -> Server.유저 정보 관리.회원 정보 확인: 사용자 인증 및 결제 {
    style.font-size: 54
    style.stroke-width: 6
}
Server.유저 정보 관리.회원 정보 확인 -> Server.예약 처리.예약 처리: 인증 결과 전달{
    style.font-size: 54
    style.stroke-width: 6
}
Server.식당 정보.식당 정보 요청 -> Server.유저 정보 관리.회원 정보 확인: 사용자 인증{
    style.font-size: 54
    style.stroke-width: 6
}
Server.유저 정보 관리.회원 정보 확인 -> Server.식당 정보.데이터 베이스 요청: 인증 결과 전달{
    style.font-size: 54
    style.stroke-width: 6
}


# 로그인 및 회원가입 플로우
User.웹 페이지 접속 -> Server.유저 정보 관리.회원가입{
    style.font-size: 54
    style.stroke-width: 6
}
User.웹 페이지 접속 -> Server.유저 정보 관리.로그인{
    style.font-size: 54
    style.stroke-width: 6
}

# 예약 플로우
User.웹 페이지 접속 -> Server.식당 정보.식당 정보 요청: 식당 정보 받아오기{
    style.font-size: 54
    style.stroke-width: 6
}
User.식당 정보 확인 -> Server.예약 처리.예약 요청: 예약 요청{
    style.font-size: 54
    style.stroke-width: 6
}
Server.예약 처리.예약 처리 -> Restourant: 예약자 정보 전달{
    style.font-size: 54
    style.stroke-width: 6
}

